import { z } from "zod";
import { csvString, rawPayloadSchema } from "./common";

export const generalDeliveryCsvRowSchema = z.object({
  company: csvString,
  series: csvString,
  date: csvString,
  number: csvString,
  fiscalYear: csvString,
  storeCode: csvString,
  storeName: csvString,
  customerCode: csvString,
  customerName: csvString,
  lineNumber: csvString,
  itemCode: csvString,
  description: csvString,
  description2: csvString,
  supplierReference: csvString,
  warehouse: csvString,
  quantity: csvString,
  price: csvString,
  total: csvString,
  installerCodeOrName: csvString,
  warehouseSeller: csvString,
  familyLevel1: csvString,
  supplierCodeAndName: csvString,
  brandCodeAndName: csvString,
  sellerCodeOrName: csvString,
  grossAmount: csvString,
  discounts: csvString,
  taxableBase: csvString,
  vatRate: csvString,
  vatAmount: csvString,
  surchargeRate: csvString,
  surchargeAmount: csvString,
  subtotal: csvString,
  deliveryTotal: csvString,
  rawPayload: rawPayloadSchema,
});

export const supplierDeliveryCsvRowSchema = z.object({
  warehouse: csvString,
  familyLevel1: csvString,
  storeCode: csvString,
  series: csvString,
  documentType: csvString,
  number: csvString,
  orderNumber: csvString,
  lineNumber: csvString,
  documentDate: csvString,
  customerCode: csvString,
  itemCode: csvString,
  description: csvString,
  quantitySum: csvString,
  salesBaseSum: csvString,
  supplierCodeAndName: csvString,
  brandCodeAndName: csvString,
  rawPayload: rawPayloadSchema,
});

export const sellerDeliveryCsvRowSchema = z.object({
  sellerCode: csvString,
  sellerName: csvString,
  company: csvString,
  series: csvString,
  number: csvString,
  fiscalYear: csvString,
  date: csvString,
  serviceDate: csvString,
  customerCode: csvString,
  customerName: csvString,
  storeCode: csvString,
  grossAmount: csvString,
  discounts: csvString,
  taxableBase: csvString,
  vatAmount: csvString,
  surchargeAmount: csvString,
  total: csvString,
  createdByUser: csvString,
  createdAtSource: csvString,
  rawPayload: rawPayloadSchema,
});

export const installerDeliveryCsvRowSchema = sellerDeliveryCsvRowSchema.extend({
  installerCode: csvString,
  installerName: csvString,
});

