import { z } from "zod";
import { csvString, rawPayloadSchema, resolvedFlagSchema } from "./common";

export const incidentCsvRowSchema = z.object({
  incidentClass: csvString,
  number: csvString,
  state: csvString,
  stateType: csvString,
  date: csvString,
  storeCode: csvString,
  storeName: csvString,
  supplierCode: csvString,
  supplierName: csvString,
  brandName: csvString,
  phonePrimary: csvString,
  fax: csvString,
  openDuration: csvString,
  customerCode: csvString,
  customerName: csvString,
  phoneSecondary: csvString,
  truck: csvString,
  sellerCode: csvString,
  sellerName: csvString,
  orderFiscalYear: csvString,
  orderSeries: csvString,
  orderNumber: csvString,
  referencePrimary: csvString,
  deliveryFiscalYear: csvString,
  deliverySeries: csvString,
  deliveryNumber: csvString,
  itemCode: csvString,
  description: csvString,
  description2: csvString,
  referenceSecondary: csvString,
  quantity: csvString,
  incidentType: csvString,
  severity: csvString,
  lastReceptionDate: csvString,
  resolved: resolvedFlagSchema.or(csvString),
  resolvedDate: csvString,
  solution: csvString,
  createdAtSource: csvString,
  associatedExpenses: csvString,
  cost: csvString,
  rawPayload: rawPayloadSchema,
});

export type IncidentCsvRowInput = z.infer<typeof incidentCsvRowSchema>;

